local ops = require('overleaf.ops')

describe('ops', function()
  describe('path validation', function()
    it('normalizes leading slashes and repeated slashes', function()
      local path, err = ops._validate_path('/sections//intro.tex')
      assert.is_nil(err)
      assert.are.equal('sections/intro.tex', path)
    end)

    it('rejects empty paths', function()
      local path, err = ops._validate_path('')
      assert.is_nil(path)
      assert.are.equal('Path cannot be empty', err)
    end)

    it('rejects parent traversal', function()
      local path, err = ops._validate_path('../secret.tex')
      assert.is_nil(path)
      assert.matches('%.%.?', err)
    end)

    it('rejects current-directory traversal', function()
      local path, err = ops._validate_path('./main.tex')
      assert.is_nil(path)
      assert.matches('%.', err)
    end)

    it('rejects newline characters', function()
      local path, err = ops._validate_path('bad\nname.tex')
      assert.is_nil(path)
      assert.matches('newlines', err)
    end)

    it('rejects nested paths when validating a name', function()
      local path, err = ops._validate_path('sections/intro.tex', { kind = 'name' })
      assert.is_nil(path)
      assert.matches('Name cannot contain /', err)
    end)
  end)
end)
